---
- name: Yolo Environment
  hosts: yolo_vm  # as per the vagrant file
  become: yes
  tasks:
    - name: Clone Code from GitHub
      git:
        repo: https://github.com/Kkigathi/IP_Docker.git # URL for my own git repo
        dest: /devops04/IP_Ansible/IP_Ansible
      tags:
        - clone
    - name: Install Docker #docker installation on the VM we created
      apt:
        name: docker.io
        state: present
      tags:
        - docker
    