---
- name: Yolo Environment
  hosts: yolo_vm  # as per the vagrant file
  become: yes
  tasks:
    - name: Clone Code from GitHub
      git:
        repo: https://github.com/Kkigathi/IP_Ansible.git # URL for my own git repo
        dest: /devops04/IP_Ansible/IP_Ansible/.vagrant
      tags:
        - clone
    - name: Install Docker #docker installation on the VM we created
      apt:
        name: docker.io
        state: present
      tags:
        - docker
    - name: Copy ROOT Docker Compose Files
      copy:
        src: /devops04/IP_Ansible/IP_Ansible/docker-compose.yml
        dest: /devops04/IP_Ansible/IP_Ansible/.vagrant
      tags:
        - docker-compose
   # - name: Copy backend Docker Files
    #  copy:
     #   src: /devops04/IP_Ansible/IP_Ansible/backend/Dockerfile
     #   dest: /devops04/IP_Ansible/IP_Ansible/.vagrant
     # tags:
     #   - docker-compose
     #didnt need to copy docker files to ansibele
          